apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-redis-config
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-redis-config
    helm.sh/chart: {{ include "spiritbomb.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: redis-configmap
data:
  redis-config: |
    save 900 1
    save 300 10
    save 60 10000
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes
    dbfilename dump.rdb
    appendonly yes
    appendfilename "redis.aof"
    appendfsync everysec
    no-appendfsync-on-rewrite no
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb
    aof-load-truncated yes
    aof-use-rdb-preamble yes
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-chain-credentials
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-chain-credentials
    helm.sh/chart: {{ include "spiritbomb.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: chain-credentials
data:
  chain-credentials: |-
{{ .Files.Get "files/credentials" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-controller-values
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-controller-values
    helm.sh/chart: {{ include "spiritbomb.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: controller-values
data:
  targetRate: "{{ .Values.controller.targetRate }}"
  maxWorkers: "{{ div .Values.chainPoolCount .Values.worker.threads }}"
