kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-account
automountServiceAccountToken: false
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-account
rules:
- apiGroups: ["apps", "extensions"]
  resources: ["deployments", "deployments/scale"]
  verbs: ["get", "list", "watch", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-account
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-account
  apiGroup: ""
roleRef:
  kind: Role
  name: {{ .Release.Name }}-account
  apiGroup: rbac.authorization.k8s.io
