stage: production

redis:
  image:
    repository: redis
    tag: 5.0.7-alpine
  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 20m
      memory: 64Mi
  storage:
    spec:
      storageClassName: aws-efs
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Mi

chainPoolCount: 10

controller:
  targetRate: 2000
  image:
    repository: 381978683274.dkr.ecr.us-west-2.amazonaws.com/spirit-bomb
    tag: 1.0.7
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 500Mi

worker:
  threads: 2
  bulk: 1000
  image:
    repository: 381978683274.dkr.ecr.us-west-2.amazonaws.com/spirit-bomb
    tag: 1.0.7
  resources:
    limits:
      cpu: 2
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 1024Mi
